# Generated by Django 5.0.6 on 2024-05-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('joining_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('hired_on', models.DateField(blank=True, null=True)),
                ('days_employed', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
