# Generated by Django 5.0.6 on 2024-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
